mod variable_location;
mod variable_value;
mod expr_location;

mod identity;
mod equivalence;
mod insertion;

use crate::expressions::assigned::binding::bounds::{TblExpressionBoundAtomExactValue, TblExpressionBoundAtomExistsAtLocation, TblExpressionBoundCompoundExactLength, TblExpressionBoundCompoundExistsAtLocation, TblExpressionBoundValueDuplicated};

pub type UnassignedTblExpressionBoundAtomExistsAtLocation = TblExpressionBoundAtomExistsAtLocation;
pub type UnassignedTblPropositionBoundAtomExistsAtLocation = UnassignedTblExpressionBoundAtomExistsAtLocation;
pub type UnassignedTblExpressionBoundAtomExactValue = TblExpressionBoundAtomExactValue;
pub type UnassignedTblPropositionBoundAtomExactValue = UnassignedTblExpressionBoundAtomExactValue;
pub type UnassignedTblExpressionBoundCompoundExistsAtLocation = TblExpressionBoundCompoundExistsAtLocation;
pub type UnassignedTblPropositionBoundCompoundExistsAtLocation = UnassignedTblExpressionBoundCompoundExistsAtLocation;
pub type UnassignedTblExpressionBoundCompoundExactLength = TblExpressionBoundCompoundExactLength;
pub type UnassignedTblPropositionBoundCompoundExactLength = UnassignedTblExpressionBoundCompoundExactLength;
pub use variable_location::{UnassignedTblExpressionBoundVariableExistsAtLocation,UnassignedTblPropositionBoundVariableExistsAtLocation};
pub use variable_value::{UnassignedTblExpressionBoundVariableExactValue,UnassignedTblPropositionBoundVariableExactValue};
pub use expr_location::{UnassignedTblExpressionBoundExpressionExistsAtLocation,UnassignedTblPropositionBoundExpressionExistsAtLocation,AtomOrVariableOrCompoundLength};
pub type UnassignedTblExpressionBoundValueDuplicated = TblExpressionBoundValueDuplicated;
pub type UnassignedTblPropositionBoundValueDuplicated = UnassignedTblExpressionBoundValueDuplicated;

pub use identity::{UnassignedTblExpressionIdentityBound,UnassignedTblPropositionIdentityBound};
pub use equivalence::{UnassignedTblExpressionEquivalenceBound,TblPropositionEquivalenceBound};
pub use insertion::{UnassignedTblExpressionInsertionBound,UnassignedTblPropositionSubsumedBound};
