[package]
name = "tbl_stringification"
version = "0.1.0"
edition = "2024"

[dependencies]
tbl_structures = { path = "../structures" }

bimap = { version = "0.6.3" }
enum-iterator = { version = "2.1.0" }
either = { version = "1.15.0" }