mod conjunction_introduction;
mod implication_elimination;
mod universal_substitution;

pub use conjunction_introduction::verify_conjunction_introduction;
pub use implication_elimination::verify_implication_elimination;
pub use universal_substitution::verify_universal_substitution;
